configVersion: v1
metadata:
  author: Example
  id: test-123
  namespace: default
configuration:
  - name: encrypted
    value: encrypted-value
    encrypted: true
  - name: unencrypted
    value: unencrypted-value
    encrypted: false
