configVersion: v1
metadata:
  author: Example
  id: test-123
configuration:
  - name: encrypted
    value: encrypted-value
    encrypted: true
    namespace: default
  - name: unencrypted
    value: unencrypted-value
    encrypted: false
    namespace: default
